# -*- coding: utf-8 -*-
"""Análise de dados - vendas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gHzcBzXumFyAtAY8iWD8O_vkbUqI-813

## **Análise de dados - vendas**
---

Nesse _notebook_, o nosso desafio é analisar 6 planilhas de excel sobre vendas realizadas nos meses de janeiro, fevereiro, março, abril, maio e junho. E, identificar qual vendedor realizou vendas maior que `55.000` e, para posteriormente enviar um **SMS** para o meu telefone.

❗**Obs:** para realizar o envio do **SMS** será necessário a instalação da biblioteca `twilio`.

Para utilizar a `API` do _twilio_ é necessário realizar um cadastro gratuito na plataforma (site) para gerar as chaves de autenticação que será utilizadas para o envio do **SMS**.

Link: https://www.twilio.com/docs/libraries/python

Instalando a biblioteca `twilio`.
"""

!pip install twilio

# importando a biblioteca "pandas" e a função "Client" da biblioteca "twilio"
import pandas as pd                 # para análise e manipulação de dados
from twilio.rest import Client      # para habilitar o envio do SMS

# abrindo e visualizando a planilha do mês de janeiro e suas 5 primeiras linhas
planilhaVendas_JAN = pd.read_excel('janeiro.xlsx')
print(f'\n{planilhaVendas_JAN.head()}')

# instanciando uma lista com nome dos meses
lista_meses = ['janeiro', 'fevereiro', 'março',
               'abril', 'maio', 'junho']

lista_meses

# realizando um laço de repetição para abrir as planilhas dos meses
for mes in lista_meses:
    # print(mes)
    planilhasVendas_SEMESTRE = pd.read_excel(f'{mes}.xlsx')
    print(planilhasVendas_SEMESTRE, sep='\n')

# utilizando a biblioteca "twilio" para enviar o SMS
# Your Account SID from twilio.com/console | O SID da sua conta em twilio.com/console
account_sid = "AC423c28335ae82a2032847960dcaac791"
# Your Auth Token from twilio.com/console | Seu token de autenticação em twilio.com/console
auth_token  = "your_auth_token"

# instanciando o objeto "client"
client = Client(account_sid, auth_token)

# realizando um laço de repetição para abrir as planilhas dos meses
for mes in lista_meses:
    # print(mes)
    planilhasVendas_SEMESTRE = pd.read_excel(f'{mes}.xlsx')
    # print(planilhasVendas_SEMESTRE, sep='\n')

    if (planilhasVendas_SEMESTRE['Vendas'] > 55_000).any():
        vendedor = planilhasVendas_SEMESTRE.loc[(planilhasVendas_SEMESTRE['Vendas'] > 55_000), 'Vendedor'].values[0]
        vendas = planilhasVendas_SEMESTRE.loc[(planilhasVendas_SEMESTRE['Vendas'] > 55_000), 'Vendas'].values[0]
        print(f'No mês de "{mes}" o vendedor "{vendedor}" obteve o valor de "R$ {vendas}" em vendas!')

        # gerando e enviando a mensagem SMS para seu telefone
        message = client.messages.create(
            to="+55xxxxxxxxxx",    # instanciar seu número de telefone
            from_="+xxxxxxxxxxx",   # instanciar o seu número do "telefone" gerado pelo "twilio"
            body=f'\nNo mês de "{mes}" o vendedor "{vendedor}" obteve o valor de "R$ {vendas}" em vendas!')
        print(message.sid)  # resposta do envio do SMS

"""Instalando a biblioteca `info` para visualizar a versão das bibliotecas/funções utilizadas nesse _notebook_."""

!pip install session_info

# importando a biblioteca
import session_info

# visualizando as versões das bibliotecas e/ou funções utilizadas no notebook
session_info.show(html=False)

